export const referenceSources = [
  { title: 'NCSL · 50-state bill tracking', url: 'https://www.ncsl.org/technology-and-communication/ncsl-50-state-searchable-bill-tracking-databases', scope: 'State policy · legislation' },
  { title: 'NACo · County economic profiles', url: 'https://ce.naco.org/?dset=County%20Economies&ind=County%20Economies%20Profiles', scope: 'County economies · interactive dashboard' },
  { title: 'ECS · State education legislation', url: 'https://www.ecs.org/state-legislation-by-state/', scope: 'State policy · education' },
  { title: 'Workforce Almanac', url: 'https://workforcealmanac.com/explore', scope: 'Workforce institutions · downloadable data' },
  { title: 'National Zoning Atlas', url: 'https://www.zoningatlas.org/atlas', scope: 'Local land use · coverage varies' },
  { title: 'Zillow research data', url: 'https://www.zillow.com/research/data/', scope: 'Housing · rents · affordability · downloadable data' },
  { title: 'HUD · Building permits', url: 'https://www.huduser.gov/socds/permits/', scope: 'Housing · construction' },
  { title: 'Harvard Dataverse · requested research dataset', url: 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NJTBEM', scope: 'Research dataset · verify documentation before use' },
  { title: 'LocalView · Public meetings', url: 'https://www.localview.net/', scope: 'Local government · public deliberation' },
  { title: 'Apprenticeships by state', url: 'https://www.apprenticeship.gov/data-and-statistics/apprentices-by-state-dashboard', scope: 'State workforce · apprenticeships' },
  { title: 'Subsidy Tracker', url: 'https://subsidytracker.goodjobsfirst.org/', scope: 'Business incentives · policy records' },
  { title: 'CareerTech · State policy tracker', url: 'https://careertech.org/resource/state-policy-tracker/', scope: 'State education · career and technical education' },
  { title: 'Philadelphia Fed · Anchor Economy 2024 dataset', url: 'https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-Data/anchor-economy-dashboard/anchor-economy-full-dataset-2024.xlsx?sc_lang=en', scope: 'Higher education & hospitals · download XLSX and upload' },
  { title: 'NASBO · State budgets', url: 'https://www.nasbo.org/', scope: 'State finance · budget reports' },
  { title: 'Urban Institute · State and local finance data', url: 'https://state-local-finance-data.urban.org/', scope: 'Government finance · budgets' },
  { title: 'BLS · Occupational Employment and Wage Statistics', url: 'https://www.bls.gov/oes/', scope: 'Occupation statistics · state and metro (not county estimates)' },
  { title: 'BLS · Local Area Unemployment Statistics', url: 'https://www.bls.gov/lau/', scope: 'Employment · state/county/city' },
  { title: 'BLS · Current Employment Statistics', url: 'https://www.bls.gov/ces/', scope: 'Industry payroll employment · check geographic coverage' },
  { title: 'Census · American Community Survey', url: 'https://www.census.gov/programs-surveys/acs', scope: 'Demographics · industry · occupation' },
  { title: 'Census · State and local government finance', url: 'https://www.census.gov/programs-surveys/gov-finances.html', scope: 'Finance · education spending · verify release year' },
  {
    title: "ADAPT research data & methodology",
    url: "https://github.com/cgsp-georgetown/adapt-viz",
    scope: "National · county outcomes",
  },
  {
    title: "Census QuickFacts · Shelby County, Ohio",
    url: "https://www.census.gov/quickfacts/shelbycountyohio",
    scope: "Shelby County, OH",
  },
  {
    title: "Census QuickFacts · Auglaize County, Ohio",
    url: "https://www.census.gov/quickfacts/auglaizecountyohio",
    scope: "Auglaize County, OH",
  },
  {
    title: "Ohio county economic profiles",
    url: "https://ohiolmi.com/Home/Dashboards/CountyEconomicProfiles",
    scope: "Ohio · employment & business",
  },
  {
    title: "Ohio labor-market data search",
    url: "https://ohiolmi.com/DataSearch",
    scope: "Ohio · labor market",
  },
  {
    title: "BEA · GDP by county",
    url: "https://www.bea.gov/data/gdp/gdp-by-county",
    scope: "National · county economy",
  },
  {
    title: "BEA · Regional economic facts",
    url: "https://apps.bea.gov/regional/bearfacts/",
    scope: "National · county economy",
  },
  {
    title: "BLS · Quarterly Census of Employment and Wages",
    url: "https://www.bls.gov/cew/data.htm",
    scope: "National · jobs & wages",
  },
  {
    title: "WEF · Future of Jobs Report 2025",
    url: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/in-full/2-jobs-outlook/",
    scope: "Global · AI & jobs",
  },
  {
    title: "McKinsey · Generative AI and the future of work in America",
    url: "https://www.mckinsey.com/mgi/our-research/generative-ai-and-the-future-of-work-in-america",
    scope: "US · AI & workforce",
  },
  {
    title: "IMF · Gen-AI: Artificial Intelligence and the Future of Work",
    url: "https://www.elibrary.imf.org/view/journals/006/2024/001/article-A001-en.xml",
    scope: "Global · AI exposure",
  },
  {
    title: "ILO · Generative AI and Jobs: 2025 update",
    url: "https://www.ilo.org/publications/generative-ai-and-jobs-2025-update",
    scope: "Global · occupational transformation",
  },
  {
    title: "Goldman Sachs · AI and the US labor market",
    url: "https://www.goldmansachs.com/insights/articles/how-will-ai-affect-the-us-labor-market",
    scope: "US · labor market",
  },
  {
    title: "IFR · The impact of robots on employment and jobs",
    url: "https://ifr.org/papers/the-impact-of-robots-on-employment-and-jobs",
    scope: "Global · robotics",
  },
  {
    title: "Anthropic · Economic Index survey",
    url: "https://www.anthropic.com/research/economic-index-survey-announcement",
    scope: "AI · usage evidence",
  },
];
