export const helpSections = [
  { id: 'start', title: '1. Explore a county', text: 'Search by county name, state abbreviation or FIPS. The first county chip is your reference county; click another chip to make it the reference. Add up to four counties and remove peers with ×. Select a map measure to see its original ADAPT values. The data are historical, through 2022—not current conditions.', prompt: 'What are the major industries in this county?' },
  { id: 'compare', title: '2. Compare places', text: 'Open Peer comparison or choose Compare this pair on a county’s matched-peer card. Compare outcomes, historical trends, industries and occupations. Headline 2022 measures and historical series are separately constructed and must not be substituted. A difference is a question to investigate, not proof of a policy’s effect. Download comparison CSV to take the displayed values with you.', prompt: 'Which differences between these counties are observed, and what remains unknown?' },
  { id: 'chat', title: '3. Ask and follow up', text: 'Use the evidence companion beneath the map, comparison or scenario workspace. Select a suggested question, then click Send or press Enter. Shift+Enter adds a new line. Ask follow-ups freely. The context label shows the current tool and counties; changing the county selection changes the next question’s context. Previous answers are historical records, not automatically refreshed.', prompt: 'What evidence supports that answer? What would contradict it?' },
  { id: 'connect', title: '4. Connect an AI model', text: 'Open AI connection. Choose OpenRouter or OpenAI, enter your own key and choose an available tool-capable model. OpenRouter offers GPT Luna, GPT-4.1 and GPT-4.1 mini immediately, without loading a catalog. Switching to OpenRouter selects GPT Luna by default. Model access and credits belong to your provider account. Built-in testing is available only if explicitly enabled for your account. Keys stay in this tab’s session storage and are sent through the server to the selected provider, not saved in conversations. Clear keys explicitly when finished; browser session restore may retain them.' },
  { id: 'sources', title: '5. Add documents and websites', text: 'In Evidence library, an administrator can upload PDF, DOCX, XLSX, CSV, TXT or Markdown files (up to 8 MB and 300,000 extracted characters). Scanned PDFs need OCR. Give the source a title, county/state scope and publication/data-period notes. Websites need a Firecrawl key with credits: index a specific public HTTPS page, not a whole site. Dynamic dashboards may require downloading their underlying data and uploading it instead. Wait for Indexed, then Inspect the passages before using them. The library is shared with authorized site users; do not upload confidential material without permission.' },
  { id: 'audit', title: '6. Audit and remove evidence', text: 'Open Audit evidence beneath an answer to inspect its saved citations and excerpts. Reference shelf links are discovery aids—not indexed evidence. To check a source’s effect, ask the same question in a new investigation before and after indexing, then compare the cited passages. Removing a source excludes it from new searches; old answers retain historical citations. Start a new investigation for a clean comparison.' },
  { id: 'policy', title: '7. Document peer policies', text: 'Peer comparison includes a policy register and dated timeline. Administrators can attach a policy record to an indexed source and an exact supporting passage. Record its county, adoption date (if known), status and reported outcomes. Records disappear from active results when their supporting source is removed. An implementation date on a timeline does not establish that the policy caused wage or employment changes.', prompt: 'List documented policies in these counties, their dates and the evidence of outcomes.' },
  { id: 'future', title: '8. Explore scenarios responsibly', text: 'Policy simulator uses the V2 ADAPT dashboard’s published four-lever formula and its current raw county inputs. Choose the reference county, adjust export exposure, per-pupil spending, downstream trade exposure or import competition, and compare the current and projected qualitative levels. Reset returns every lever to the selected county’s baseline. A scenario response is not a causal estimate, budget forecast or prediction. Record assumptions in the notes, then ask about AI, robotics, trade or 2030 with explicit uncertainty.', prompt: 'Under slower and faster AI adoption, what could change by 2030, and what evidence would distinguish these scenarios?' },
  { id: 'save', title: '9. Resume and download', text: 'Investigations contains your saved conversations. Opening one restores its last county selection. Download a conversation as Markdown including citations, or download the displayed comparison as CSV. Your conversations are private to your signed-in account; the evidence library is shared.' },
  { id: 'trouble', title: 'Troubleshooting', text: 'If Send opens AI connection, configure a key and save, then resend the preserved draft. Authentication errors need a valid key; rate/spending limits need provider credits or a retry later. Website indexing failures can mean insufficient Firecrawl credits, a protected page or no readable content. Upload an authorized document as an alternative. If simulator inputs fail to load, retry after checking the V2 ADAPT data service. Missing source evidence should produce an explicit gap—not an invented answer.' },
];
